// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GotoPoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#ifndef ____GotoPoint_h__
#define ____GotoPoint_h__

#include <Ice/ProxyF.h>
#include <Ice/ObjectF.h>
#include <Ice/Exception.h>
#include <Ice/LocalObject.h>
#include <Ice/StreamHelpers.h>
#include <Ice/Proxy.h>
#include <Ice/Object.h>
#include <Ice/Outgoing.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/Incoming.h>
#include <Ice/Direct.h>
#include <IceUtil/ScopedArray.h>
#include <IceUtil/Optional.h>
#include <Ice/StreamF.h>
#include <Ice/UndefSysMacros.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace IceProxy
{

namespace RoboCompGotoPoint
{

class GotoPoint;
void __read(::IceInternal::BasicStream*, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompGotoPoint::GotoPoint>&);
::IceProxy::Ice::Object* upCast(::IceProxy::RoboCompGotoPoint::GotoPoint*);

}

}

namespace RoboCompGotoPoint
{

class GotoPoint;
bool operator==(const GotoPoint&, const GotoPoint&);
bool operator<(const GotoPoint&, const GotoPoint&);
::Ice::Object* upCast(::RoboCompGotoPoint::GotoPoint*);
typedef ::IceInternal::Handle< ::RoboCompGotoPoint::GotoPoint> GotoPointPtr;
typedef ::IceInternal::ProxyHandle< ::IceProxy::RoboCompGotoPoint::GotoPoint> GotoPointPrx;
void __patch(GotoPointPtr&, const ::Ice::ObjectPtr&);

}

namespace RoboCompGotoPoint
{

class Callback_GotoPoint_go_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GotoPoint_go_Base> Callback_GotoPoint_goPtr;

class Callback_GotoPoint_turn_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GotoPoint_turn_Base> Callback_GotoPoint_turnPtr;

class Callback_GotoPoint_atTarget_Base : virtual public ::IceInternal::CallbackBase { };
typedef ::IceUtil::Handle< Callback_GotoPoint_atTarget_Base> Callback_GotoPoint_atTargetPtr;

}

namespace IceProxy
{

namespace RoboCompGotoPoint
{

class GotoPoint : virtual public ::IceProxy::Ice::Object
{
public:

    void go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha)
    {
        go(nodo, x, y, alpha, 0);
    }
    void go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context& __ctx)
    {
        go(nodo, x, y, alpha, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_go(nodo, x, y, alpha, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_go(nodo, x, y, alpha, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_go(nodo, x, y, alpha, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_go(nodo, x, y, alpha, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha)
    {
        return begin_go(nodo, x, y, alpha, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context& __ctx)
    {
        return begin_go(nodo, x, y, alpha, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(nodo, x, y, alpha, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(nodo, x, y, alpha, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::RoboCompGotoPoint::Callback_GotoPoint_goPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(nodo, x, y, alpha, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context& __ctx, const ::RoboCompGotoPoint::Callback_GotoPoint_goPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_go(nodo, x, y, alpha, &__ctx, __del, __cookie);
    }

    void end_go(const ::Ice::AsyncResultPtr&);
    
private:

    void go(const ::std::string&, ::Ice::Float, ::Ice::Float, ::Ice::Float, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_go(const ::std::string&, ::Ice::Float, ::Ice::Float, ::Ice::Float, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    void turn(::Ice::Float speed)
    {
        turn(speed, 0);
    }
    void turn(::Ice::Float speed, const ::Ice::Context& __ctx)
    {
        turn(speed, &__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_turn(speed, 0, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent));
    }
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_turn(speed, 0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::IceInternal::Function<void ()>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return begin_turn(speed, &__ctx, new ::IceInternal::Cpp11FnOnewayCallbackNC(__response, __exception, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_turn(speed, &__ctx, ::Ice::newCallback(__completed, __sent));
    }
#endif

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed)
    {
        return begin_turn(speed, 0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx)
    {
        return begin_turn(speed, &__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, &__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::RoboCompGotoPoint::Callback_GotoPoint_turnPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, 0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_turn(::Ice::Float speed, const ::Ice::Context& __ctx, const ::RoboCompGotoPoint::Callback_GotoPoint_turnPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_turn(speed, &__ctx, __del, __cookie);
    }

    void end_turn(const ::Ice::AsyncResultPtr&);
    
private:

    void turn(::Ice::Float, const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_turn(::Ice::Float, const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:

    bool atTarget()
    {
        return atTarget(0);
    }
    bool atTarget(const ::Ice::Context& __ctx)
    {
        return atTarget(&__ctx);
    }
#ifdef ICE_CPP11
    ::Ice::AsyncResultPtr
    begin_atTarget(const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_atTarget(0, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_atTarget(const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_atTarget(0, ::Ice::newCallback(__completed, __sent), 0);
    }
    ::Ice::AsyncResultPtr
    begin_atTarget(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception = ::IceInternal::Function<void (const ::Ice::Exception&)>(), const ::IceInternal::Function<void (bool)>& __sent = ::IceInternal::Function<void (bool)>())
    {
        return __begin_atTarget(&__ctx, __response, __exception, __sent);
    }
    ::Ice::AsyncResultPtr
    begin_atTarget(const ::Ice::Context& __ctx, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __completed, const ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>& __sent = ::IceInternal::Function<void (const ::Ice::AsyncResultPtr&)>())
    {
        return begin_atTarget(&__ctx, ::Ice::newCallback(__completed, __sent));
    }
    
private:

    ::Ice::AsyncResultPtr __begin_atTarget(const ::Ice::Context* __ctx, const ::IceInternal::Function<void (bool)>& __response, const ::IceInternal::Function<void (const ::Ice::Exception&)>& __exception, const ::IceInternal::Function<void (bool)>& __sent)
    {
        class Cpp11CB : public ::IceInternal::Cpp11FnCallbackNC
        {
        public:

            Cpp11CB(const ::std::function<void (bool)>& responseFunc, const ::std::function<void (const ::Ice::Exception&)>& exceptionFunc, const ::std::function<void (bool)>& sentFunc) :
                ::IceInternal::Cpp11FnCallbackNC(exceptionFunc, sentFunc),
                _response(responseFunc)
            {
                CallbackBase::checkCallback(true, responseFunc || exceptionFunc != nullptr);
            }

            virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
            {
                ::RoboCompGotoPoint::GotoPointPrx __proxy = ::RoboCompGotoPoint::GotoPointPrx::uncheckedCast(__result->getProxy());
                bool __ret;
                try
                {
                    __ret = __proxy->end_atTarget(__result);
                }
                catch(::Ice::Exception& ex)
                {
                    Cpp11FnCallbackNC::__exception(__result, ex);
                    return;
                }
                if(_response != nullptr)
                {
                    _response(__ret);
                }
            }
        
        private:
            
            ::std::function<void (bool)> _response;
        };
        return begin_atTarget(__ctx, new Cpp11CB(__response, __exception, __sent));
    }
    
public:
#endif

    ::Ice::AsyncResultPtr begin_atTarget()
    {
        return begin_atTarget(0, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_atTarget(const ::Ice::Context& __ctx)
    {
        return begin_atTarget(&__ctx, ::IceInternal::__dummyCallback, 0);
    }

    ::Ice::AsyncResultPtr begin_atTarget(const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_atTarget(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_atTarget(const ::Ice::Context& __ctx, const ::Ice::CallbackPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_atTarget(&__ctx, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_atTarget(const ::RoboCompGotoPoint::Callback_GotoPoint_atTargetPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_atTarget(0, __del, __cookie);
    }

    ::Ice::AsyncResultPtr begin_atTarget(const ::Ice::Context& __ctx, const ::RoboCompGotoPoint::Callback_GotoPoint_atTargetPtr& __del, const ::Ice::LocalObjectPtr& __cookie = 0)
    {
        return begin_atTarget(&__ctx, __del, __cookie);
    }

    bool end_atTarget(const ::Ice::AsyncResultPtr&);
    
private:

    bool atTarget(const ::Ice::Context*);
    ::Ice::AsyncResultPtr begin_atTarget(const ::Ice::Context*, const ::IceInternal::CallbackBasePtr&, const ::Ice::LocalObjectPtr& __cookie = 0);
    
public:
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_context(const ::Ice::Context& __context) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_context(__context).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_adapterId(const ::std::string& __id) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_adapterId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_endpoints(const ::Ice::EndpointSeq& __endpoints) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_endpoints(__endpoints).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_locatorCacheTimeout(int __timeout) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_locatorCacheTimeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_connectionCached(bool __cached) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_connectionCached(__cached).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_endpointSelection(::Ice::EndpointSelectionType __est) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_endpointSelection(__est).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_secure(bool __secure) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_secure(__secure).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_preferSecure(bool __preferSecure) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_preferSecure(__preferSecure).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_router(const ::Ice::RouterPrx& __router) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_router(__router).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_locator(const ::Ice::LocatorPrx& __locator) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_locator(__locator).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_collocationOptimized(bool __co) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_collocationOptimized(__co).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_twoway() const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_twoway().get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_oneway() const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_oneway().get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_batchOneway() const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_batchOneway().get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_datagram() const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_datagram().get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_batchDatagram() const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_batchDatagram().get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_compress(bool __compress) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_compress(__compress).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_timeout(int __timeout) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_timeout(__timeout).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_connectionId(const ::std::string& __id) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_connectionId(__id).get());
    }
    
    ::IceInternal::ProxyHandle<GotoPoint> ice_encodingVersion(const ::Ice::EncodingVersion& __v) const
    {
        return dynamic_cast<GotoPoint*>(::IceProxy::Ice::Object::ice_encodingVersion(__v).get());
    }
    
    static const ::std::string& ice_staticId();

private: 

    virtual ::IceInternal::Handle< ::IceDelegateM::Ice::Object> __createDelegateM();
    virtual ::IceInternal::Handle< ::IceDelegateD::Ice::Object> __createDelegateD();
    virtual ::IceProxy::Ice::Object* __newInstance() const;
};

}

}

namespace IceDelegate
{

namespace RoboCompGotoPoint
{

class GotoPoint : virtual public ::IceDelegate::Ice::Object
{
public:

    virtual void go(const ::std::string&, ::Ice::Float, ::Ice::Float, ::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual void turn(::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;

    virtual bool atTarget(const ::Ice::Context*, ::IceInternal::InvocationObserver&) = 0;
};

}

}

namespace IceDelegateM
{

namespace RoboCompGotoPoint
{

class GotoPoint : virtual public ::IceDelegate::RoboCompGotoPoint::GotoPoint,
                  virtual public ::IceDelegateM::Ice::Object
{
public:

    virtual void go(const ::std::string&, ::Ice::Float, ::Ice::Float, ::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void turn(::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool atTarget(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace IceDelegateD
{

namespace RoboCompGotoPoint
{

class GotoPoint : virtual public ::IceDelegate::RoboCompGotoPoint::GotoPoint,
                  virtual public ::IceDelegateD::Ice::Object
{
public:

    virtual void go(const ::std::string&, ::Ice::Float, ::Ice::Float, ::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual void turn(::Ice::Float, const ::Ice::Context*, ::IceInternal::InvocationObserver&);

    virtual bool atTarget(const ::Ice::Context*, ::IceInternal::InvocationObserver&);
};

}

}

namespace RoboCompGotoPoint
{

class GotoPoint : virtual public ::Ice::Object
{
public:

    typedef GotoPointPrx ProxyType;
    typedef GotoPointPtr PointerType;

    virtual bool ice_isA(const ::std::string&, const ::Ice::Current& = ::Ice::Current()) const;
    virtual ::std::vector< ::std::string> ice_ids(const ::Ice::Current& = ::Ice::Current()) const;
    virtual const ::std::string& ice_id(const ::Ice::Current& = ::Ice::Current()) const;
    static const ::std::string& ice_staticId();

    virtual void go(const ::std::string&, ::Ice::Float, ::Ice::Float, ::Ice::Float, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___go(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual void turn(::Ice::Float, const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___turn(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual bool atTarget(const ::Ice::Current& = ::Ice::Current()) = 0;
    ::Ice::DispatchStatus ___atTarget(::IceInternal::Incoming&, const ::Ice::Current&);

    virtual ::Ice::DispatchStatus __dispatch(::IceInternal::Incoming&, const ::Ice::Current&);

protected:
    virtual void __writeImpl(::IceInternal::BasicStream*) const;
    virtual void __readImpl(::IceInternal::BasicStream*);
    #ifdef __SUNPRO_CC
    using ::Ice::Object::__writeImpl;
    using ::Ice::Object::__readImpl;
    #endif
};

inline bool operator==(const GotoPoint& l, const GotoPoint& r)
{
    return static_cast<const ::Ice::Object&>(l) == static_cast<const ::Ice::Object&>(r);
}

inline bool operator<(const GotoPoint& l, const GotoPoint& r)
{
    return static_cast<const ::Ice::Object&>(l) < static_cast<const ::Ice::Object&>(r);
}

}

namespace RoboCompGotoPoint
{

template<class T>
class CallbackNC_GotoPoint_go : public Callback_GotoPoint_go_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_GotoPoint_go(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_GotoPoint_goPtr
newCallback_GotoPoint_go(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_go<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GotoPoint_goPtr
newCallback_GotoPoint_go(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_go<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_GotoPoint_goPtr
newCallback_GotoPoint_go(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_go<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GotoPoint_goPtr
newCallback_GotoPoint_go(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_go<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_GotoPoint_go : public Callback_GotoPoint_go_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_GotoPoint_go(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_GotoPoint_goPtr
newCallback_GotoPoint_go(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_go<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GotoPoint_goPtr
newCallback_GotoPoint_go(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_go<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_GotoPoint_goPtr
newCallback_GotoPoint_go(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_go<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GotoPoint_goPtr
newCallback_GotoPoint_go(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_go<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_GotoPoint_turn : public Callback_GotoPoint_turn_Base, public ::IceInternal::OnewayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)();

    CallbackNC_GotoPoint_turn(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallbackNC<T>(obj, cb, excb, sentcb)
    {
    }
};

template<class T> Callback_GotoPoint_turnPtr
newCallback_GotoPoint_turn(const IceUtil::Handle<T>& instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_turn<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GotoPoint_turnPtr
newCallback_GotoPoint_turn(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_turn<T>(instance, 0, excb, sentcb);
}

template<class T> Callback_GotoPoint_turnPtr
newCallback_GotoPoint_turn(T* instance, void (T::*cb)(), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_turn<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GotoPoint_turnPtr
newCallback_GotoPoint_turn(T* instance, void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_turn<T>(instance, 0, excb, sentcb);
}

template<class T, typename CT>
class Callback_GotoPoint_turn : public Callback_GotoPoint_turn_Base, public ::IceInternal::OnewayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(const CT&);

    Callback_GotoPoint_turn(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::OnewayCallback<T, CT>(obj, cb, excb, sentcb)
    {
    }
};

template<class T, typename CT> Callback_GotoPoint_turnPtr
newCallback_GotoPoint_turn(const IceUtil::Handle<T>& instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_turn<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GotoPoint_turnPtr
newCallback_GotoPoint_turn(const IceUtil::Handle<T>& instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_turn<T, CT>(instance, 0, excb, sentcb);
}

template<class T, typename CT> Callback_GotoPoint_turnPtr
newCallback_GotoPoint_turn(T* instance, void (T::*cb)(const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_turn<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GotoPoint_turnPtr
newCallback_GotoPoint_turn(T* instance, void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_turn<T, CT>(instance, 0, excb, sentcb);
}

template<class T>
class CallbackNC_GotoPoint_atTarget : public Callback_GotoPoint_atTarget_Base, public ::IceInternal::TwowayCallbackNC<T>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception&);
    typedef void (T::*Sent)(bool);
    typedef void (T::*Response)(bool);

    CallbackNC_GotoPoint_atTarget(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallbackNC<T>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompGotoPoint::GotoPointPrx __proxy = ::RoboCompGotoPoint::GotoPointPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_atTarget(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::CallbackNC<T>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::CallbackNC<T>::callback.get()->*response)(__ret);
        }
    }

    Response response;
};

template<class T> Callback_GotoPoint_atTargetPtr
newCallback_GotoPoint_atTarget(const IceUtil::Handle<T>& instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_atTarget<T>(instance, cb, excb, sentcb);
}

template<class T> Callback_GotoPoint_atTargetPtr
newCallback_GotoPoint_atTarget(T* instance, void (T::*cb)(bool), void (T::*excb)(const ::Ice::Exception&), void (T::*sentcb)(bool) = 0)
{
    return new CallbackNC_GotoPoint_atTarget<T>(instance, cb, excb, sentcb);
}

template<class T, typename CT>
class Callback_GotoPoint_atTarget : public Callback_GotoPoint_atTarget_Base, public ::IceInternal::TwowayCallback<T, CT>
{
public:

    typedef IceUtil::Handle<T> TPtr;

    typedef void (T::*Exception)(const ::Ice::Exception& , const CT&);
    typedef void (T::*Sent)(bool , const CT&);
    typedef void (T::*Response)(bool, const CT&);

    Callback_GotoPoint_atTarget(const TPtr& obj, Response cb, Exception excb, Sent sentcb)
        : ::IceInternal::TwowayCallback<T, CT>(obj, cb != 0, excb, sentcb), response(cb)
    {
    }

    virtual void __completed(const ::Ice::AsyncResultPtr& __result) const
    {
        ::RoboCompGotoPoint::GotoPointPrx __proxy = ::RoboCompGotoPoint::GotoPointPrx::uncheckedCast(__result->getProxy());
        bool __ret;
        try
        {
            __ret = __proxy->end_atTarget(__result);
        }
        catch(::Ice::Exception& ex)
        {
            ::IceInternal::Callback<T, CT>::__exception(__result, ex);
            return;
        }
        if(response)
        {
            (::IceInternal::Callback<T, CT>::callback.get()->*response)(__ret, CT::dynamicCast(__result->getCookie()));
        }
    }

    Response response;
};

template<class T, typename CT> Callback_GotoPoint_atTargetPtr
newCallback_GotoPoint_atTarget(const IceUtil::Handle<T>& instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_atTarget<T, CT>(instance, cb, excb, sentcb);
}

template<class T, typename CT> Callback_GotoPoint_atTargetPtr
newCallback_GotoPoint_atTarget(T* instance, void (T::*cb)(bool, const CT&), void (T::*excb)(const ::Ice::Exception&, const CT&), void (T::*sentcb)(bool, const CT&) = 0)
{
    return new Callback_GotoPoint_atTarget<T, CT>(instance, cb, excb, sentcb);
}

}

#endif
