// **********************************************************************
//
// Copyright (c) 2003-2013 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.5.1
//
// <auto-generated>
//
// Generated from file `GotoPoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <GotoPoint.h>
#include <Ice/LocalException.h>
#include <Ice/ObjectFactory.h>
#include <Ice/BasicStream.h>
#include <Ice/Object.h>
#include <IceUtil/Iterator.h>

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 305
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 > 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 1
#       error Ice patch level mismatch!
#   endif
#endif

namespace
{

const ::std::string __RoboCompGotoPoint__GotoPoint__go_name = "go";

const ::std::string __RoboCompGotoPoint__GotoPoint__turn_name = "turn";

const ::std::string __RoboCompGotoPoint__GotoPoint__atTarget_name = "atTarget";

}
::IceProxy::Ice::Object* ::IceProxy::RoboCompGotoPoint::upCast(::IceProxy::RoboCompGotoPoint::GotoPoint* p) { return p; }

void
::IceProxy::RoboCompGotoPoint::__read(::IceInternal::BasicStream* __is, ::IceInternal::ProxyHandle< ::IceProxy::RoboCompGotoPoint::GotoPoint>& v)
{
    ::Ice::ObjectPrx proxy;
    __is->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new ::IceProxy::RoboCompGotoPoint::GotoPoint;
        v->__copyFrom(proxy);
    }
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompGotoPoint__GotoPoint__go_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompGotoPoint::GotoPoint* __del = dynamic_cast< ::IceDelegate::RoboCompGotoPoint::GotoPoint*>(__delBase.get());
            __del->go(nodo, x, y, alpha, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::begin_go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompGotoPoint__GotoPoint__go_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompGotoPoint__GotoPoint__go_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(nodo);
        __os->write(x);
        __os->write(y);
        __os->write(alpha);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::end_go(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompGotoPoint__GotoPoint__go_name);
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::turn(::Ice::Float speed, const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompGotoPoint__GotoPoint__turn_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompGotoPoint::GotoPoint* __del = dynamic_cast< ::IceDelegate::RoboCompGotoPoint::GotoPoint*>(__delBase.get());
            __del->turn(speed, __ctx, __observer);
            return;
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::begin_turn(::Ice::Float speed, const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompGotoPoint__GotoPoint__turn_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompGotoPoint__GotoPoint__turn_name, ::Ice::Normal, __ctx);
        ::IceInternal::BasicStream* __os = __result->__startWriteParams(::Ice::DefaultFormat);
        __os->write(speed);
        __result->__endWriteParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

void
IceProxy::RoboCompGotoPoint::GotoPoint::end_turn(const ::Ice::AsyncResultPtr& __result)
{
    __end(__result, __RoboCompGotoPoint__GotoPoint__turn_name);
}

bool
IceProxy::RoboCompGotoPoint::GotoPoint::atTarget(const ::Ice::Context* __ctx)
{
    ::IceInternal::InvocationObserver __observer(this, __RoboCompGotoPoint__GotoPoint__atTarget_name, __ctx);
    int __cnt = 0;
    while(true)
    {
        ::IceInternal::Handle< ::IceDelegate::Ice::Object> __delBase;
        try
        {
            __checkTwowayOnly(__RoboCompGotoPoint__GotoPoint__atTarget_name);
            __delBase = __getDelegate(false);
            ::IceDelegate::RoboCompGotoPoint::GotoPoint* __del = dynamic_cast< ::IceDelegate::RoboCompGotoPoint::GotoPoint*>(__delBase.get());
            return __del->atTarget(__ctx, __observer);
        }
        catch(const ::IceInternal::LocalExceptionWrapper& __ex)
        {
            __handleExceptionWrapper(__delBase, __ex, __observer);
        }
        catch(const ::Ice::LocalException& __ex)
        {
            __handleException(__delBase, __ex, true, __cnt, __observer);
        }
    }
}

::Ice::AsyncResultPtr
IceProxy::RoboCompGotoPoint::GotoPoint::begin_atTarget(const ::Ice::Context* __ctx, const ::IceInternal::CallbackBasePtr& __del, const ::Ice::LocalObjectPtr& __cookie)
{
    __checkAsyncTwowayOnly(__RoboCompGotoPoint__GotoPoint__atTarget_name);
    ::IceInternal::OutgoingAsyncPtr __result = new ::IceInternal::OutgoingAsync(this, __RoboCompGotoPoint__GotoPoint__atTarget_name, __del, __cookie);
    try
    {
        __result->__prepare(__RoboCompGotoPoint__GotoPoint__atTarget_name, ::Ice::Normal, __ctx);
        __result->__writeEmptyParams();
        __result->__send(true);
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __result->__exceptionAsync(__ex);
    }
    return __result;
}

bool
IceProxy::RoboCompGotoPoint::GotoPoint::end_atTarget(const ::Ice::AsyncResultPtr& __result)
{
    ::Ice::AsyncResult::__check(__result, this, __RoboCompGotoPoint__GotoPoint__atTarget_name);
    bool __ret;
    bool __ok = __result->__wait();
    try
    {
        if(!__ok)
        {
            try
            {
                __result->__throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                throw ::Ice::UnknownUserException(__FILE__, __LINE__, __ex.ice_name());
            }
        }
        ::IceInternal::BasicStream* __is = __result->__startReadParams();
        __is->read(__ret);
        __result->__endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& ex)
    {
        __result->__getObserver().failed(ex.ice_name());
        throw;
    }
}

const ::std::string&
IceProxy::RoboCompGotoPoint::GotoPoint::ice_staticId()
{
    return ::RoboCompGotoPoint::GotoPoint::ice_staticId();
}

::IceInternal::Handle< ::IceDelegateM::Ice::Object>
IceProxy::RoboCompGotoPoint::GotoPoint::__createDelegateM()
{
    return ::IceInternal::Handle< ::IceDelegateM::Ice::Object>(new ::IceDelegateM::RoboCompGotoPoint::GotoPoint);
}

::IceInternal::Handle< ::IceDelegateD::Ice::Object>
IceProxy::RoboCompGotoPoint::GotoPoint::__createDelegateD()
{
    return ::IceInternal::Handle< ::IceDelegateD::Ice::Object>(new ::IceDelegateD::RoboCompGotoPoint::GotoPoint);
}

::IceProxy::Ice::Object*
IceProxy::RoboCompGotoPoint::GotoPoint::__newInstance() const
{
    return new GotoPoint;
}

void
IceDelegateM::RoboCompGotoPoint::GotoPoint::go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompGotoPoint__GotoPoint__go_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(nodo);
        __os->write(x);
        __os->write(y);
        __os->write(alpha);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

void
IceDelegateM::RoboCompGotoPoint::GotoPoint::turn(::Ice::Float speed, const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompGotoPoint__GotoPoint__turn_name, ::Ice::Normal, __context, __observer);
    try
    {
        ::IceInternal::BasicStream* __os = __og.startWriteParams(::Ice::DefaultFormat);
        __os->write(speed);
        __og.endWriteParams();
    }
    catch(const ::Ice::LocalException& __ex)
    {
        __og.abort(__ex);
    }
    bool __ok = __og.invoke();
    if(__og.hasResponse())
    {
        try
        {
            if(!__ok)
            {
                try
                {
                    __og.throwUserException();
                }
                catch(const ::Ice::UserException& __ex)
                {
                    ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                    throw __uue;
                }
            }
            __og.readEmptyParams();
        }
        catch(const ::Ice::LocalException& __ex)
        {
            throw ::IceInternal::LocalExceptionWrapper(__ex, false);
        }
    }
}

bool
IceDelegateM::RoboCompGotoPoint::GotoPoint::atTarget(const ::Ice::Context* __context, ::IceInternal::InvocationObserver& __observer)
{
    ::IceInternal::Outgoing __og(__handler.get(), __RoboCompGotoPoint__GotoPoint__atTarget_name, ::Ice::Normal, __context, __observer);
    __og.writeEmptyParams();
    bool __ok = __og.invoke();
    bool __ret;
    try
    {
        if(!__ok)
        {
            try
            {
                __og.throwUserException();
            }
            catch(const ::Ice::UserException& __ex)
            {
                ::Ice::UnknownUserException __uue(__FILE__, __LINE__, __ex.ice_name());
                throw __uue;
            }
        }
        ::IceInternal::BasicStream* __is = __og.startReadParams();
        __is->read(__ret);
        __og.endReadParams();
        return __ret;
    }
    catch(const ::Ice::LocalException& __ex)
    {
        throw ::IceInternal::LocalExceptionWrapper(__ex, false);
    }
}

void
IceDelegateD::RoboCompGotoPoint::GotoPoint::go(const ::std::string& nodo, ::Ice::Float x, ::Ice::Float y, ::Ice::Float alpha, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(const ::std::string& __p_nodo, ::Ice::Float __p_x, ::Ice::Float __p_y, ::Ice::Float __p_alpha, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_nodo(__p_nodo),
            _m_x(__p_x),
            _m_y(__p_y),
            _m_alpha(__p_alpha)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompGotoPoint::GotoPoint* servant = dynamic_cast< ::RoboCompGotoPoint::GotoPoint*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->go(_m_nodo, _m_x, _m_y, _m_alpha, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        const ::std::string& _m_nodo;
        ::Ice::Float _m_x;
        ::Ice::Float _m_y;
        ::Ice::Float _m_alpha;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompGotoPoint__GotoPoint__go_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(nodo, x, y, alpha, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

void
IceDelegateD::RoboCompGotoPoint::GotoPoint::turn(::Ice::Float speed, const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(::Ice::Float __p_speed, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _m_speed(__p_speed)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompGotoPoint::GotoPoint* servant = dynamic_cast< ::RoboCompGotoPoint::GotoPoint*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            servant->turn(_m_speed, _current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        ::Ice::Float _m_speed;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompGotoPoint__GotoPoint__turn_name, ::Ice::Normal, __context);
    try
    {
        _DirectI __direct(speed, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
}

bool
IceDelegateD::RoboCompGotoPoint::GotoPoint::atTarget(const ::Ice::Context* __context, ::IceInternal::InvocationObserver&)
{
    class _DirectI : public ::IceInternal::Direct
    {
    public:

        _DirectI(bool& __result, const ::Ice::Current& __current) : 
            ::IceInternal::Direct(__current),
            _result(__result)
        {
        }
        
        virtual ::Ice::DispatchStatus
        run(::Ice::Object* object)
        {
            ::RoboCompGotoPoint::GotoPoint* servant = dynamic_cast< ::RoboCompGotoPoint::GotoPoint*>(object);
            if(!servant)
            {
                throw ::Ice::OperationNotExistException(__FILE__, __LINE__, _current.id, _current.facet, _current.operation);
            }
            _result = servant->atTarget(_current);
            return ::Ice::DispatchOK;
        }
        
    private:
        
        bool& _result;
    };
    
    ::Ice::Current __current;
    __initCurrent(__current, __RoboCompGotoPoint__GotoPoint__atTarget_name, ::Ice::Normal, __context);
    bool __result;
    try
    {
        _DirectI __direct(__result, __current);
        try
        {
            __direct.getServant()->__collocDispatch(__direct);
        }
        catch(...)
        {
            __direct.destroy();
            throw;
        }
        __direct.destroy();
    }
    catch(const ::Ice::SystemException&)
    {
        throw;
    }
    catch(const ::IceInternal::LocalExceptionWrapper&)
    {
        throw;
    }
    catch(const ::std::exception& __ex)
    {
        ::IceInternal::LocalExceptionWrapper::throwWrapper(__ex);
    }
    catch(...)
    {
        throw ::IceInternal::LocalExceptionWrapper(::Ice::UnknownException(__FILE__, __LINE__, "unknown c++ exception"), false);
    }
    return __result;
}

::Ice::Object* RoboCompGotoPoint::upCast(::RoboCompGotoPoint::GotoPoint* p) { return p; }

namespace
{
const ::std::string __RoboCompGotoPoint__GotoPoint_ids[2] =
{
    "::Ice::Object",
    "::RoboCompGotoPoint::GotoPoint"
};

}

bool
RoboCompGotoPoint::GotoPoint::ice_isA(const ::std::string& _s, const ::Ice::Current&) const
{
    return ::std::binary_search(__RoboCompGotoPoint__GotoPoint_ids, __RoboCompGotoPoint__GotoPoint_ids + 2, _s);
}

::std::vector< ::std::string>
RoboCompGotoPoint::GotoPoint::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&__RoboCompGotoPoint__GotoPoint_ids[0], &__RoboCompGotoPoint__GotoPoint_ids[2]);
}

const ::std::string&
RoboCompGotoPoint::GotoPoint::ice_id(const ::Ice::Current&) const
{
    return __RoboCompGotoPoint__GotoPoint_ids[1];
}

const ::std::string&
RoboCompGotoPoint::GotoPoint::ice_staticId()
{
    return __RoboCompGotoPoint__GotoPoint_ids[1];
}

::Ice::DispatchStatus
RoboCompGotoPoint::GotoPoint::___go(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::std::string nodo;
    ::Ice::Float x;
    ::Ice::Float y;
    ::Ice::Float alpha;
    __is->read(nodo);
    __is->read(x);
    __is->read(y);
    __is->read(alpha);
    __inS.endReadParams();
    go(nodo, x, y, alpha, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompGotoPoint::GotoPoint::___turn(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    ::IceInternal::BasicStream* __is = __inS.startReadParams();
    ::Ice::Float speed;
    __is->read(speed);
    __inS.endReadParams();
    turn(speed, __current);
    __inS.__writeEmptyParams();
    return ::Ice::DispatchOK;
}

::Ice::DispatchStatus
RoboCompGotoPoint::GotoPoint::___atTarget(::IceInternal::Incoming& __inS, const ::Ice::Current& __current)
{
    __checkMode(::Ice::Normal, __current.mode);
    __inS.readEmptyParams();
    bool __ret = atTarget(__current);
    ::IceInternal::BasicStream* __os = __inS.__startWriteParams(::Ice::DefaultFormat);
    __os->write(__ret);
    __inS.__endWriteParams(true);
    return ::Ice::DispatchOK;
}

namespace
{
const ::std::string __RoboCompGotoPoint__GotoPoint_all[] =
{
    "atTarget",
    "go",
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "turn"
};

}

::Ice::DispatchStatus
RoboCompGotoPoint::GotoPoint::__dispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair< const ::std::string*, const ::std::string*> r = ::std::equal_range(__RoboCompGotoPoint__GotoPoint_all, __RoboCompGotoPoint__GotoPoint_all + 7, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - __RoboCompGotoPoint__GotoPoint_all)
    {
        case 0:
        {
            return ___atTarget(in, current);
        }
        case 1:
        {
            return ___go(in, current);
        }
        case 2:
        {
            return ___ice_id(in, current);
        }
        case 3:
        {
            return ___ice_ids(in, current);
        }
        case 4:
        {
            return ___ice_isA(in, current);
        }
        case 5:
        {
            return ___ice_ping(in, current);
        }
        case 6:
        {
            return ___turn(in, current);
        }
    }

    assert(false);
    throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
}

void
RoboCompGotoPoint::GotoPoint::__writeImpl(::IceInternal::BasicStream* __os) const
{
    __os->startWriteSlice(ice_staticId(), -1, true);
    __os->endWriteSlice();
}

void
RoboCompGotoPoint::GotoPoint::__readImpl(::IceInternal::BasicStream* __is)
{
    __is->startReadSlice();
    __is->endReadSlice();
}

void 
RoboCompGotoPoint::__patch(GotoPointPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = ::RoboCompGotoPoint::GotoPointPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(::RoboCompGotoPoint::GotoPoint::ice_staticId(), v);
    }
}
